.\"groff -Tascii -man snapclient.1
.TH SNAPCLIENT 1 "September 2025"
.SH NAME
snapclient - Snapcast client
.SH SYNOPSIS
\fBsnapclient\fR [\fIOPTION\fR]...
.SH DESCRIPTION
Snapcast is a multiroom client-server audio player, where all clients are
time synchronized with the server to play perfectly synced audio. It's not a
standalone player, but an extension that turns your existing audio player into
a Sonos-like multiroom solution.
.br
The server's audio input is a named pipe `/tmp/snapfifo`. All data that is fed
into this file will be send to the connected clients. One of the most generic
ways to use Snapcast is in conjunction with the music player daemon or Mopidy,
which can be configured to use a named pipe as audio output.
.SS Usage: snapclient [options...] [url]

 With 'url' = <tcp|ws|wss>://<snapserver host or IP or mDNS service name>[:port]
 For example: 'tcp://192.168.1.1:1704', or 'ws://)homeserver.local' or 'wss://_snapcast-https._tcp'
 If 'url' is not configured, snapclient defaults to 'tcp://_snapcast._tcp'
:
.TP
\fB--help\fR
Produce help message
.TP
\fB-v, --version\fR
Show version number
.TP
\fB-h, --host arg\fR
(deprecated, use [url]) Server hostname or ip address
.TP
\fB-p, --port arg (=1704)\fR
(deprecated, use [url]) Server port
.TP
\fB-i, --instance arg (=1)\fR
Instance id when running multiple instances on the same host
.TP
\fB--hostID arg\fR
Unique host id, default is MAC address
.TP
\fB--cert arg (="")\fR
Client certificate file (PEM format)
.TP
\fB--cert-key arg (="")\fR
Client private key file (PEM format)
.TP
\fB--key-password arg\fR
Key password (for encrypted private key)
.TP
\fB--server-cert [=arg(="default certificates")]\fR
Verify server with CA certificate (PEM format)
.TP
\fB-l, --list\fR
List PCM devices
.TP
\fB-s, --soundcard arg (=default)\fR
Index or name of the PCM device
.TP
\fB--latency arg (=0)\fR
Latency of the PCM device
.TP
\fB--sampleformat arg\fR
Resample audio stream to <rate>:<bits>:<channels>
.TP
\fB--player arg (=alsa)\fR
alsa|pipewire|file[:<options>|?]
.TP
\fB--mixer arg (=software)\fR
software|hardware|script|none|?[:<options>]
.TP
\fB-d, --daemon [=arg(=-3)]\fR
Daemonize, optional process priority [-20..19]
.TP
\fB--user arg\fR
The user[:group] to run snapclient as when daemonized
.TP
\fB--logsink arg\fR
Log sink [null,system,stdout,stderr,file:<filename>]
.TP
\fB--logfilter arg (=*:info)\fR
Log filter <tag>:<level>[,<tag>:<level>]* with tag = * or <log tag> and level = [trace,debug,info,notice,warning,error,fatal]
.SH FILES
.TP
\fI/etc/default/snapclient\fR
the daemon default configuration file
.SH "COPYRIGHT"
Copyright (C) 2014-2025 Johannes Pohl (snapcast@badaix.de).
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
snapserver(1)
