.\"groff -Tascii -man snapclient.1
.TH SNAPCLIENT 1 "December 2015"
.SH NAME
snapclient - Snapcast client
.SH SYNOPSIS
\fBsnapclient\fR [\fIOPTION\fR]...
.SH DESCRIPTION
Snapcast is a multi-room client-server audio player, where all clients are
time synchronized with the server to play perfectly synced audio. It's not a
standalone player, but an extension that turns your existing audio player into
a Sonos-like multi-room solution.
.br
The server's audio input is a named pipe `/tmp/snapfifo`. All data that is fed
into this file will be send to the connected clients. One of the most generic
ways to use Snapcast is in conjunction with the music player daemon or Mopidy,
which can be configured to use a named pipe as audio output.
.SS Options
.TP
\fB--help\fR
produce help message
.TP
\fB-v, --version\fR
show version number
.TP
\fB-l, --list\fR
list pcm devices
.TP
\fB-h, --host\fR
server hostname or ip address
.TP
\fB-p, --port\fR
server port
.TP
\fB-s, --soundcard\fR
index or name of the soundcard
.TP
\fB-d, --daemon\fR
daemonize, optional process priority [-20..19]
.TP
\fB--latency\fR
latency of the soundcard
.SH FILES
.TP
\fI/etc/default/snapclient\fR
the daemon default configuration file
.SH "COPYRIGHT"
Copyright (C) 2014-2016 Johannes Pohl (johannes.pohl@badaix.de).
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
snapserver(1)
