#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/snapclient" ] || [ -e "/etc/init/snapclient.conf" ]; then
	invoke-rc.d snapclient stop || exit $?
fi
# End automatically added section
