#!/bin/sh

set -e

USERNAME=_snapclient
HOMEDIR=/var/lib/snapclient

if [ "$1" = configure ]; then
  if ! getent passwd _snapclient >/dev/null; then
    adduser --system --quiet --group --home /var/lib/snapclient --no-create-home --force-badname $USERNAME
    adduser $USERNAME audio
  fi

  if [ ! -d $HOMEDIR ]; then
    mkdir -m 0750 $HOMEDIR
    chown $USERNAME:$USERNAME $HOMEDIR
  fi
fi

#DEBHELPER#
