#!/bin/sh
set -e
# Automatically added by dh_systemd_enable
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask snapserver.service >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled snapserver.service; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable snapserver.service >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state snapserver.service >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/snapserver" ] || [ -e "/etc/init/snapserver.conf" ]; then
	if [ ! -e "/etc/init/snapserver.conf" ]; then
		update-rc.d snapserver defaults >/dev/null
	fi
	invoke-rc.d snapserver start || exit $?
fi
# End automatically added section
