#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/snapserver" ] || [ -e "/etc/init/snapserver.conf" ]; then
	invoke-rc.d snapserver stop || exit $?
fi
# End automatically added section
