#!/bin/sh

set -e

if [ "$1" = "purge" ]; then
	# clean up all statoverrides that belonged to snapserver, so the
	# snapserver system user can be removed cleanly
	for i in $(dpkg-statoverride --list | awk '/^snapserver / {print $4}'); do
		if dpkg-statoverride --list --quiet "$i" >/dev/null; then
			dpkg-statoverride --force --quiet --remove "$i"
		fi
	done
fi

userdel --force snapserver > /dev/null || true
groupdel snapserver > /dev/null || true

#DEBHELPER#
