name: Raspbian-armhf

on: [push, pull_request]

jobs:
  build:

    runs-on: self-hosted-rpi3
    steps:
    - uses: actions/checkout@v1
    - name: ps
      run: ps aeuxwww
    - name: env
      run: env
