SET(CMAKE_SYSTEM_NAME Windows)
SET(CMAKE_C_COMPILER /usr/bin/x86_64-w64-mingw32-gcc)
SET(CMAKE_CXX_COMPILER /usr/bin/x86_64-w64-mingw32-g++)
SET(CMAKE_FIND_ROOT_PATH  /usr/bin/i686-w64-mingw32 /home/joseph/workspace/snapcast/externals/target)
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_SYSROOT /home/joseph/workspace/snapcast/externals/target)
SET(CMAKE_CXX_FLAGS "-L/home/joseph/workspace/snapcast/externals/target/lib" CACHE STRING "" FORCE)
